version: '3'

services:
  httpd:
    container_name: ${CONTAINER_NAME_PREFIX}httpd
    build:
      context: httpd
      args:
        - HTTPD_VERSION=${HTTPD_VERSION}
        - HTTPD_OS_VERSION=${HTTPD_OS_VERSION}
    environment:
      - CI_ENVIRONMENT
      - HTTPD_SERVER_NAME
    volumes:
      - type: bind
        source: ../
        target: /usr/local/apache2/codeigniter
    ports:
      - "80:80"
      - "443:443"
  php:
    container_name: ${CONTAINER_NAME_PREFIX}php
    build:
      context: php
      args:
        - PHP_VERSION=${PHP_VERSION}
        - PHP_OS_VERSION=${PHP_OS_VERSION}
    environment:
      - CI_APP_API_ACCESS_CONTROL_ALLOW_ORIGIN
      - CI_APP_API_KEY
      - CI_APP_ENCRYPTION_KEY
      - CI_APP_DB_HOST
      - CI_APP_DB_USER
      - CI_APP_DB_PASSWORD
      - CI_APP_DB_NAME
      - CI_APP_DB_PORT
    volumes:
      - type: bind
        source: ./htdocs
        target: /usr/local/apache2/htdocs
      - type: bind
        source: ../
        target: /usr/local/apache2/codeigniter
  db:
    container_name: ${CONTAINER_NAME_PREFIX}db
    build:
      context: db
    environment:
      - POSTGRES_PASSWORD=${CI_APP_DB_PASSWORD}
      - POSTGRES_USER=${CI_APP_DB_USER}
      - POSTGRES_DB=${CI_APP_DB_NAME}
    ports:
      - "5432:5432"
